Features/categories
Pavlo2005/project-group-14 pull request #21
Opened 2023-09-19 20:10 UTC by AnnaKudas

Created the sidebar for category selection. Please review. @Pavlo2005

2023-09-20 07:17 UTC, Pavlo2005 commented on src/css/03-categories.css
> +@media screen and (min-width: 415px) {
не можна прописувати загальні стилі ніде крім styles.css

2023-09-20 07:19 UTC, Pavlo2005 requested changes

2023-09-20 07:19 UTC, Pavlo2005 commented on src/css/03-categories.css
> +@media screen and (max-width: 414px) {
не можна прописувати загальні стилі ніде крім styles.css

2023-09-20 07:19 UTC, Pavlo2005 commented on src/css/03-categories.css
> +  .container {
не можна прописувати загальні стилі ніде крім styles.css

2023-09-20 07:19 UTC, Pavlo2005 commented on src/css/03-categories.css
> +  .container {
не можна прописувати загальні стилі ніде крім styles.css

2023-09-20 18:09 UTC, oomloud requested changes
1. не вірно прописана мобільна версія. Треба так:
- 320-375рх - мобільна тянучка
- 375-768рх - мобільний адаптив
- 768-1280рх - таблетний адаптив
- 1280рх - десктоп
2.  не задані стилі для самої секції `category-section`, тому на мобілці виглядає невірно
![image](https://github.com/Pavlo2005/project-group-14/assets/47818790/30d3efce-2669-4b5d-b969-ccf305f1e1c1)
![image](https://github.com/Pavlo2005/project-group-14/assets/47818790/cf667362-30bc-4a9f-9de2-02ce9dd4bc4a)

2023-09-20 18:09 UTC, oomloud commented on src/partials/03-categories.html
> +<link rel="stylesheet" href="../css/03-categories.css" />
посилання на стилі можна прибрати адже вони додані до index.htm

2023-09-20 18:09 UTC, oomloud commented on src/css/03-categories.css
> +@media screen and (min-width: 415px) {
не прописані стилі для мобільної версії від 320px до 415px

2023-09-20 18:09 UTC, oomloud commented on src/css/03-categories.css
> +@media screen and (max-width: 414px) {
мобільну версію можна писати без @media і всі базові властивості на ній, а таблет і десктоп - тільки різниці

2023-09-21 19:04 UTC, Pavlo2005 approved these changes

2023-09-21 19:04 UTC, oomloud approved these changes

2023-09-21 19:04 UTC, merged