Features/header
Pavlo2005/project-group-14 pull request #22
Opened 2023-09-20 08:11 UTC by VladBryzhak

Ніби все працює, але я ще можливо додам зміну стану світчера. Також додав бекдроп, коли відкривається меню(на мобілці), якщо вам не сподобається, можу видалити його.

2023-09-20 18:33 UTC, oomloud requested changes

2023-09-20 18:33 UTC, oomloud commented on src/css/01-header.css
> +  .nav-container {
nav-container краще зробити через флекс, justify-content: space-between
інакше розбиважться верстка через марджини на лого та перемикач теми вилізає за контейнерФ
![image](https://github.com/Pavlo2005/project-group-14/assets/47818790/35048ffa-07c5-4521-885b-2c8846c0241f)
![image](https://github.com/Pavlo2005/project-group-14/assets/47818790/eab98fdb-cb6d-4424-94e2-06643694ad40)
![image](https://github.com/Pavlo2005/project-group-14/assets/47818790/af636b5d-8859-4d20-b89c-17cfef661685)

2023-09-20 18:40 UTC, VladBryzhak commented on src/css/01-header.css
> +  .nav-container {
Дивно...Коли створював пул, перевіряв, ніби нічого такого не було((( Зараз спробую виправити

2023-09-21 16:59 UTC, Pavlo2005 approved these changes

2023-09-21 18:45 UTC, merged